Fixed game restart
SerMURZIK/Snake pull request #6
Opened 2023-12-25 12:49 UTC by SerMURZIK

It fixed

2024-01-17 14:55 UTC, KirichenkovMichael commented
может таки сделать 1 метод и передавать панель нужную в него?


а то они одинаковые, а внутри только разные панели используются


и что-то надо с описанием и использованием multi/single panel сделать, они что-то больно одинаковые, либо с наследованием и оверрайдом что-то делать, либо вообще один класс с параметром в конструкторе

2024-01-17 14:57 UTC, KirichenkovMichael requested changes

2024-01-17 14:57 UTC, KirichenkovMichael commented on src/main/java/classes/other/GameWindow.java
> +    private void addMultiplayerKeyListener() {
может таки сделать 1 метод и передавать панель нужную в него?

2024-01-17 14:57 UTC, KirichenkovMichael commented on src/main/java/classes/other/GameWindow.java
> +    private void addMultiplayerKeyListener() {
а то они одинаковые, а внутри только разные панели используются

2024-01-17 14:57 UTC, KirichenkovMichael commented on src/main/java/classes/other/GameWindow.java
> +    private void addMultiplayerKeyListener() {
и что-то надо с описанием и использованием multi/single panel сделать, они что-то больно одинаковые, либо с наследованием и оверрайдом что-то делать, либо вообще один класс с параметром в конструкторе

2024-01-17 16:27 UTC, SerMURZIK commented on src/main/java/classes/other/GameWindow.java
> +    private void addMultiplayerKeyListener() {
С методами разобрался, про панели буду думать

2024-01-17 16:28 UTC, kizlt commented on src/main/java/classes/other/GameWindow.java
> +    private void addMultiplayerKeyListener() {
> и что-то надо с описанием и использованием multi/single panel сделать, они что-то больно одинаковые, либо с наследованием и оверрайдом что-то делать, либо вообще один класс с параметром в конструкторе

С методами разобрался, про панели буду думать

2024-02-13 16:10 UTC, SerMURZIK commented
Товарищ, @KirichenkovMichael ! Я тут коммит с починенным рестартом сделал, можете глянуть)

2024-03-07 11:47 UTC, KirichenkovMichael commented on src/main/java/classes/other/GameWindow.java
> +    private void addMultiplayerKeyListener() {
больно долго висит пул реквест...)
тихо тут)

2024-03-25 15:39 UTC, merged